/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CashRouteImport } from './routes/cash'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as StockRouteImport } from './routes/stock'
import { Route as PartiesIdRouteImport } from './routes/parties.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIdRoute = PartiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PartiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/parties': typeof PartiesRouteWithChildren
  '/sales': typeof SalesRoute
  '/stock': typeof StockRoute
  '/parties/$id': typeof PartiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/parties': typeof PartiesRouteWithChildren
  '/sales': typeof SalesRoute
  '/stock': typeof StockRoute
  '/parties/$id': typeof PartiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/parties': typeof PartiesRouteWithChildren
  '/sales': typeof SalesRoute
  '/stock': typeof StockRoute
  '/parties/$id': typeof PartiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cash' | '/parties' | '/sales' | '/stock' | '/parties/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cash' | '/parties' | '/sales' | '/stock' | '/parties/$id'
  id:
    | '__root__'
    | '/'
    | '/cash'
    | '/parties'
    | '/sales'
    | '/stock'
    | '/parties/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashRoute: typeof CashRoute
  PartiesRoute: typeof PartiesRouteWithChildren
  SalesRoute: typeof SalesRoute
  StockRoute: typeof StockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/$id': {
      id: '/parties/$id'
      path: '/$id'
      fullPath: '/parties/$id'
      preLoaderRoute: typeof PartiesIdRouteImport
      parentRoute: typeof PartiesRoute
    }
  }
}

interface PartiesRouteChildren {
  PartiesIdRoute: typeof PartiesIdRoute
}

const PartiesRouteChildren: PartiesRouteChildren = {
  PartiesIdRoute: PartiesIdRoute,
}

const PartiesRouteWithChildren =
  PartiesRoute._addFileChildren(PartiesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashRoute: CashRoute,
  PartiesRoute: PartiesRouteWithChildren,
  SalesRoute: SalesRoute,
  StockRoute: StockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
